"""empty message

Revision ID: 2e85eaaaf8e7
Revises: 929f333a6731
Create Date: 2020-06-18 23:43:00.501718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e85eaaaf8e7'
down_revision = '929f333a6731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rooms_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=20), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('reserved_person', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rooms_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    # ### end Alembic commands ###
