"""empty message

Revision ID: 7498f97089fd
Revises: 7cf26e31f299
Create Date: 2020-06-29 00:20:14.296522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7498f97089fd'
down_revision = '7cf26e31f299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roominfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rooms_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(length=30), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rooms_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roominfo')
    # ### end Alembic commands ###
